import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/components/providers/providers";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Loading from "@/components/ui/loading";
import { GlobalAlertDialog } from "@/components/ui/alert-dialog";

export const metadata: Metadata = {
  title: "코드스테이션 | 보일러 플레이트",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.variable} suppressHydrationWarning>
      <body className={pretendard.className}>
        <Providers>
          <Header />
          <main>{children}</main>
          <Toaster />
          <Footer />
          <Loading />
          <GlobalAlertDialog />
        </Providers>
      </body>
    </html>
  );
}
